language: r
cache: packages

env:
  global:
    - secure: "ksoxMPWU651fgCmEB/BUMu0wbzFxBm7xIGZm6jclFf+EffYyAx/w7vyV3J+G/mOsKL37UjM84upNGqLmtXZR8dP6eL6cf1GVzA3ywIFSpH10RUugz5lU3XVXmWoGeXeTf4BtR+jCddbxpFTq7sJaJRNeCcKdszCKefgd5Z796xC2NRUb5KUxf6KDdUkZr8b6b3CaykUgeGgiZqJJIM0CJXYfumDksr9uEorqr6RFpOSzNFnb+Ceqp+qtK16bz/t3UsWDaETekmYqwSDoc6O9zCs5zNAZ+IsbeM2/XH0NSKVa0vY8zRh8tvbjJDRa4z7tJ/KNKUngDqhR5P5+JOp30XwPJK1a6eUnWKrCbmne+aoXY02s6Vd4D3aYxkKxoRORN3nFZGujt92xQC+EDDNkNWeamTyU9xgyYc/GrK1rgoF4u3gIBMLnLhkw4YYncPKTRv1gH05elvjAZ0XgGTN3lC+DsWUbe2zdTq+2/BFRCwAUEB9ugUNAvhOBTApw/DKYufQSudRuI4aXFjrGn+Az0FsXIaeqlqgdpuRENse7zRFeAAujVA0KSp73TzRQsXVNNkM72VSC+DF5Gz0N4r0HyeLRp0WmRMf27kn7covvkRh7TFVrjtARofxjP9BxpnqG2SyIamm2Hk5ko6nHkAZdr6i5ly55MMAe4nNmQNv2MA4="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
